version: "3"
services:
  mongodb:
    image: 'mongo'
  backend:
    build: '.'
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: feedback
        target: /app/feedback
    ports:
      - '8000:8000'

volumes:
  feedback: